[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
color-eyre = "0.6"
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
xitca-web = "0.4"

[profile.dev.package.backtrace]
opt-level = 3
