[package]
name = "yaml-headers"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
http = { workspace = true }
http-serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
