[package]
name = "html-templating"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
html5ever = { workspace = true }
markup5ever_rcdom = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
