[package]
name = "spa-loader"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
mem-server = { path = "../mem-server" }

http = { workspace = true }
mime_guess = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tracing = { workspace = true }
