name: docker

on:
  push:
    branches:
      - "**"
      - "!gh-readonly-queue/**"
    tags:
      - "v*.*.*"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.event_name != 'merge_group' }}

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-24.04
    timeout-minutes: 50
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        timeout-minutes: 5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta for sap
        id: meta-sap
        uses: docker/metadata-action@v5
        with:
          bake-target: docker-metadata-action-sap
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=${{ github.repository }}-sap
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker meta for sap-onbuild
        id: meta-sap-onbuild
        uses: docker/metadata-action@v5
        with:
          bake-target: docker-metadata-action-sap-onbuild
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=${{ github.repository }}-sap-onbuild
          flavor: |
            suffix=-onbuild,onlatest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          source: .
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-sap.outputs.bake-file }}
            ${{ steps.meta-sap-onbuild.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
